import Head from "next/head";
import Header from "../components/Header";
import db from "../config/firebase";
import Banner from "../components/Banner";
import Nearby from "../components/Nearby";
import LiveanyWhere from "../components/LiveanyWhere";
import Banner2 from "../components/Banner2";
import DiscoverExperiences from "../components/DiscoverExperiences";
import BecomeHost from "../components/BecomeHost";

export default function Home({ hotels }) {
  console.log("hotels", hotels);
  return (
    <div className="bg-gray-100 max-h-screen overflow-y-scroll">
      <Head>
        <title>Zong Hong Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header hotels={hotels} />
      <main className="mx-auto max-w-screen">
        {/*  */}
        <Banner />
        <Nearby />
        <LiveanyWhere />
        <Banner2 />
        <DiscoverExperiences />
        <BecomeHost />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const ref = db.collection("hotel");

  const hotelRes = await ref.get();
  const hotels = hotelRes.docs.map((hotel) => ({
    id: hotel.id,
    ...hotel.data(),
  }));

  return {
    props: {
      hotels: hotels,
    },
  };
}
