import Head from "next/head";
import Header from "../components/Header";
import { useEffect } from "react";
import dynamic from "next/dynamic";

//firebase
import db from "../config/firebase";

//components
const Banner = dynamic(() => import("../components/Banner"));
const Nearby = dynamic(() => import("../components/Nearby"));
const Topbar = dynamic(() => import("../components/Topbar"));
const LiveanyWhere = dynamic(() => import("../components/LiveanyWhere"));
const Banner2 = dynamic(() => import("../components/Banner2"));
const DiscoverExperiences = dynamic(() =>
  import("../components/DiscoverExperiences")
);
const BecomeHost = dynamic(() => import("../components/BecomeHost"));

//redux
import { useDispatch } from "react-redux";
import { addPlace } from "../features/placeSlice";

export default function Home({ hotels }) {
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(addPlace(hotels));
  }, [hotels]);

  return (
    <div className="bg-gray-100 max-h-screen overflow-y-scroll">
      <Head>
        <title>Zong Hong Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Topbar />
      <Header hotels={hotels} />
      <main className="mx-auto max-w-screen">
        <Banner />
        <Nearby />
        <LiveanyWhere />
        <Banner2 />
        <DiscoverExperiences />
        <BecomeHost />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const ref = db.collection("hotel");

  const hotelRes = await ref.get();
  const hotels = hotelRes.docs.map((hotel) => ({
    id: hotel.id,
    ...hotel.data(),
  }));

  return {
    props: {
      hotels: hotels,
    },
  };
}
